apiVersion: v1
kind: Namespace
metadata:
  name: walder
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-loader
  namespace: walder
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: data-loader
  template:
    metadata:
      labels:
        app: data-loader
      annotations:
        configmap/restart: "2025-08-02-19-30"
    spec:
      terminationGracePeriodSeconds: 30
      nodeSelector:
        doks.digitalocean.com/node-pool: services
      containers:
      - name: data-loader
        image: registry.digitalocean.com/walder/data-loader:main-9d39aed
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: data-loader-config
        - secretRef:
            name: clickhouse-prod  # Default to prod
        env:
        - name: NODE_ENV
          value: "production"     # Default to production
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "3Gi"
            cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: data-loader
  namespace: walder
spec:
  selector:
    app: data-loader
  ports:
  - port: 80
    targetPort: 3000