apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  namespace: walder-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: analytics-service
        image: ghcr.io/walder-ai/analytics-service:latest
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: redis-secret
        resources:
          requests:
            memory: 24Mi
            cpu: 5m
          limits:
            memory: 80Mi
            cpu: 30m
---
apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: walder-apps
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: analytics-service 