---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: analytics-service
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: analytics-service
  policy:
    alphabetical:
      order: desc
  filterTags:
    pattern: '^latest$'
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: market-fetcher
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: market-fetcher
  policy:
    alphabetical:
      order: desc
  filterTags:
    pattern: '^latest$'
