apiVersion: v1
kind: Secret
metadata:
  name: clickhouse-dev
  namespace: walder
type: Opaque
stringData:
  # ClickHouse DEV - External droplet for development
  CLICKHOUSE_URL: "https://db.walder.ai"
  CLICKHOUSE_DATABASE: "dev"
  CLICKHOUSE_USER: "walder"
  CLICKHOUSE_PASSWORD: "ntrJPV9rtv3hxb1uhp"
---
apiVersion: v1
kind: Secret
metadata:
  name: clickhouse-prod
  namespace: walder
type: Opaque
stringData:
  # ClickHouse PROD - Internal Kubernetes service
  CLICKHOUSE_URL: "http://10.114.0.5:8123"
  CLICKHOUSE_DATABASE: "prod"
  CLICKHOUSE_USER: "walder"
  CLICKHOUSE_PASSWORD: "ntrJPV9rtv3hxb1uhp"