name: Build and Deploy

on:
  push:
    branches: [ main ]
    paths: 
      - 'services/data-loader/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'services/data-loader/**'

permissions:
  contents: write
  packages: write
  pull-requests: write

env:
  REGISTRY: registry.digitalocean.com/walder
  IMAGE_NAME: data-loader

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Log in to DigitalOcean Container Registry
      uses: docker/login-action@v3
      with:
        registry: registry.digitalocean.com
        username: ${{ secrets.DO_REGISTRY_TOKEN }}
        password: ${{ secrets.DO_REGISTRY_TOKEN }}
    
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: deploy/data-loader/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        target: prod
        platforms: linux/amd64
        
    - name: Update deployment manifest
      if: github.ref == 'refs/heads/main'
      run: |
        # Get the short SHA for the image tag
        SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
        IMAGE_TAG="main-${SHORT_SHA}"
        
        # Update the deployment with new image tag
        sed -i "s|image: registry.digitalocean.com/walder/data-loader:.*|image: registry.digitalocean.com/walder/data-loader:${IMAGE_TAG}|g" deploy/data-loader/deployment.yaml
        
        # Commit the changes
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add deploy/data-loader/deployment.yaml
        git diff --staged --quiet || git commit -m "chore: update image tag to ${IMAGE_TAG} [skip ci]"
        git push